spring.datasource.url=jdbc:mysql://localhost:3306/client_task_management
spring.datasource.username=root
spring.datasource.password=Vaibhav123#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=local-development-secret